### ISSUE TITLE
How to use MinibatchKMeans on multi GPUs machine?

### ISSUE THREAD

**Issue by ZhangIceNight** [DeMoriarty/TorchPQ#17]
I'm a beginner, please how can I use multiple GPUs in MinibatchKMeans?
```
from torchpq.clustering import MinibatchKMeans
import torch

n_data = 10000 # number of data points
d_vector = 128 # dimentionality / number of features
x = torch.randn(d_vector, n_data, device="cuda")

minibatch_kmeans = MinibatchKMeans(n_clusters = 128)
minibatch_kmeans = torch.nn.DataParallel(minibatch_kmeans, device_ids=[0,1,2])
n_iter = 10
tol = 0.001
for i in range(n_iter):
    x = torch.randn(d_vector, n_data, device="cuda")
    minibatch_kmeans.fit_minibatch(x)
    if minibatch_kmeans.error < tol:
        break
```
And I get the below output
```
Traceback (most recent call last):
  File "kmean_torch.py", line 14, in <module>
    minibatch_kmeans.fit_minibatch(x)
  File "/data/home/dl/anaconda3/envs/clip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'DataParallel' object has no attribute 'fit_minibatch'
```

**Comment by DeMoriarty** [comment]
Unfortunately there isn't a multi-gpu support yet.
