### ISSUE TITLE
Import Error in Minibatch K means

### ISSUE THREAD

**Issue by mhamilton723** [DeMoriarty/TorchPQ#6]
just tried this today 
```
Traceback (most recent call last):
  File "/datadrive/phd-projects/PiCIE/eval_minimal.py", line 18, in <module>
    from torchpq.clustering import MinibatchKMeans
  File "/anaconda/envs/py38_pytorch/lib/python3.8/site-packages/torchpq/__init__.py", line 11, in <module>
    from . import experimental
ImportError: cannot import name 'experimental' from partially initialized module 'torchpq' (most likely due to a circular import) (/anaconda/envs/py38_pytorch/lib/python3.8/site-packages/torchpq/__init__.py)
```

**Comment by DeMoriarty** [comment]
it should be fixed now.

**Comment by mhamilton723** [comment]
Thanks @DeMoriarty mind pushing a new version to pip so we can remove the dependence on github installed package?

**Comment by DeMoriarty** [comment]
My bad
